version: '2.1'

services:
  collegepw-db:
    image: collegepw-db
    build: .
    command: npm start
    environment:
      NODE_ENV: production
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - "mysql"
  mysql:
      image: "mysql"
      restart: always
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: Jesusmaikinox1
